modulename: 'sbm'
filepath: 'data/SBM/exp2/CinCout_ratio1.5/'

num_run: 20

no_init: True

hierarchies: [32, 8, 2]
dropout: True
print_loss: False


gcn_layers: 3
hidden_layers: 2
hidden_dim: 64
lr: 0.0005
epochs: 2000